[package]
name = "seed"
version = "0.1.0"
edition = "2021"

[lib]
name = "seed"
path = "src/lib.rs"

[dependencies]
entity = { path = "../entity" }
cder = "0.2.0"
anyhow = "1.0.75"
sea-orm = { version = "0.12" }
