//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub mod prelude;

pub mod article;
pub mod article_tag;
pub mod comment;
pub mod favorited_article;
pub mod follower;
pub mod tag;
pub mod user;
