//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::article::Entity as Article;
pub use super::article_tag::Entity as ArticleTag;
pub use super::comment::Entity as Comment;
pub use super::favorited_article::Entity as FavoritedArticle;
pub use super::follower::Entity as Follower;
pub use super::tag::Entity as Tag;
pub use super::user::Entity as User;
